<a href="https://colab.research.google.com/github/emankhalid019/python-learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy

In [1]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [2]:
#1D Array
import numpy as np

arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [3]:
#2D Array
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
#3D Array
arr = np.array([
    [
        [1,2],
        [3,4]
    ]
])

print(arr)

[[[1 2]
  [3 4]]]


In [5]:
#NumPy Array Indexing
import numpy as np

arr=np.array([10,20,30,40])

print(arr[0])
print(arr[2])

10
30


In [6]:
#Negative Array
print(arr[-1])

40


In [7]:
#2D Indexing
arr=np.array([[10,20],[30,40]])

print(arr[1,0])

30


In [9]:
#NumPy Array Slicing
import numpy as np

arr=np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


In [10]:
#first 3 values
print(arr[:3])

[10 20 30]


In [11]:
#last 2 values
print(arr[-2:])

[40 50]


In [13]:
#array[start : stop : step]
#start = From which index starts
#stop = from which index its end (ye include nahhi hota)
#step = how many elements skip and get the target element
print(arr[::2])

[10 30 50]


In [14]:
#NumPy Data Types
import numpy as np

arr=np.array([1,2,3])

print(arr.dtype)

int64


In [15]:
#float
arr=np.array([1.5,2.5])

print(arr.dtype)

float64


In [16]:
#datatype change
arr=np.array([1,2,3])

new=arr.astype(float)

print(new)

[1. 2. 3.]


In [17]:
#NumPy Copy vs View
#if original changes copy doesnt
import numpy as np

arr=np.array([1,2,3])

x=arr.copy()

arr[0]=100

print(arr)
print(x)

[100   2   3]
[1 2 3]


In [18]:
#View
#it is linked with original array
arr=np.array([1,2,3])

x=arr.view()

arr[0]=100

print(arr)
print(x)

[100   2   3]
[100   2   3]


In [20]:
#NumPy Array Shape
#Shape made with rows and columns
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print(arr.shape)

(2, 3)


In [21]:
#NumPy Array Reshape(if shape change)
import numpy as np

arr=np.array([1,2,3,4,5,6])

new=arr.reshape(2,3)

print(new)

[[1 2 3]
 [4 5 6]]


In [22]:
#3x2
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [23]:
#NumPy Array Iterating(if loop apply)
import numpy as np

arr=np.array([10,20,30])

for i in arr:
    print(i)

10
20
30


In [24]:
#2D Loop
arr=np.array([[1,2],[3,4]])

for row in arr:
    print(row)

[1 2]
[3 4]


In [25]:
#NumPy Array Join
#if two array combines
import numpy as np

a=np.array([1,2])

b=np.array([3,4])

c=np.concatenate((a,b))

print(c)

[1 2 3 4]


In [26]:
#NumPy Array Split
#if we want to break array
import numpy as np

arr=np.array([1,2,3,4,5,6])

new=np.array_split(arr,3)

print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [27]:
#NumPy Array Search
#find the location of element
import numpy as np

arr=np.array([10,20,30,20])

x=np.where(arr==20)#20 index is on 1 and 3 index

print(x)

(array([1, 3]),)


In [30]:
#NumPy Array Sort
#Sort ascending
import numpy as np

arr=np.array([5,3,8,1])

print(np.sort(arr))
print(np.sort(arr)[::-1])#in descending we reverse thr sorted array

[1 3 5 8]
[8 5 3 1]


In [29]:
arr=np.array(["Banana","Apple","Orange"])#string

print(np.sort(arr))

['Apple' 'Banana' 'Orange']


In [32]:
#NumPy Array Filter
#on the basis of Condition get data
import numpy as np

arr=np.array([10,20,30,40,50])

new=arr[arr>25]

print(new)

[30 40 50]


In [33]:
sarr=np.array([1,2,3,4,5,6])#Even Number

print(arr[arr%2==0])

[2 4 6]


In [35]:
#NumPy Array Iteration(access the elements of array one by one)
Iteration 1
i = 10
print(i)

Iteration 2
i = 20
print(i)

Iteration 3
i = 30
print(i)

Iteration 4
i = 40
print(i)

In [36]:
import numpy as np# Array iteration

arr = np.array([10,20,30,40])
for i in arr:                         #if we want to print each value we use for loop
    print(i)

10
20
30
40


In [37]:
#2D Array Iteration
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])
#loop are on rows
for row in arr:
    print(row)

[1 2 3]
[4 5 6]


In [38]:
import numpy as np#if we want each element

arr = np.array([
    [1,2,3],
    [4,5,6]
])

for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


In [39]:
#nditer() (Professional Method)
import numpy as np

arr = np.array([
    [1,2],
    [3,4]
])

for i in np.nditer(arr):#NumPy built-in iterator is nditer() , which  accesss each element of multi-dimensional arrays
    print(i)

1
2
3
4


In [40]:
#NumPy Array Join(means combine two or more arrays in a single array)
#1D Arrays
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


In [43]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

print(np.concatenate((a,b,c)))

[1 2 3 4 5 6]


In [44]:
#Join 2D Arrays
import numpy as np

arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [5,6],
    [7,8]
])

print(np.concatenate((arr1, arr2)))# no axises means axis 0 which join rows

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
import numpy as np

arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [5,6],
    [7,8]
])

print(np.concatenate((arr1, arr2), axis=1))#axis 1 means join columns

[[1 2 5 6]
 [3 4 7 8]]


In [46]:
#Horizontal Stack also used for join
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [47]:
#Vertical Stack for join
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [48]:
#Depth Stack for join
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dstack((a,b)))

[[[1 4]
  [2 5]
  [3 6]]]


In [49]:
#NumPy Array Join
import numpy as np

a = np.array([10,20,30])
b = np.array([40,50,60])

# 1. Har element print karo
for i in a:
    print(i)

# 2. Dono arrays ko join karo
c = np.concatenate((a,b))
print(c)

# 3. Vertical stack
print(np.vstack((a,b)))

# 4. Horizontal stack
print(np.hstack((a,b)))

10
20
30
[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [50]:
#complete practice code
import numpy as np

# Create Array
arr = np.array([10,20,30,40,50,60])

print("Original:", arr)

# Indexing
print("First:", arr[0])

# Slicing
print("Slice:", arr[1:4])

# Data Type
print("Datatype:", arr.dtype)

# Reshape
new = arr.reshape(2,3)
print("Reshape:\n", new)

# Shape
print("Shape:", new.shape)

# Iteration
print("Loop:")
for i in arr:
    print(i)

# Join
a=np.array([1,2])
b=np.array([3,4])
print("Join:",np.concatenate((a,b)))

# Split
print("Split:",np.array_split(arr,3))

# Search
print("Search:",np.where(arr==40))

# Sort
x=np.array([5,3,1,4,2])
print("Sort:",np.sort(x))

# Filter
print("Greater than 30:",arr[arr>30])

Original: [10 20 30 40 50 60]
First: 10
Slice: [20 30 40]
Datatype: int64
Reshape:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Loop:
10
20
30
40
50
60
Join: [1 2 3 4]
Split: [array([10, 20]), array([30, 40]), array([50, 60])]
Search: (array([3]),)
Sort: [1 2 3 4 5]
Greater than 30: [40 50 60]
